# OpenTelemetry Collector Configuration
# This configuration defines the pipelines for data collection, processing, and export

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            -  https://*.link
            -  https://*.ai
processors:
  batch:
    # Batch processing configuration
    send_batch_size: 10000
    send_batch_max_size: 11000
    timeout: 10s
  resourcedetection:
    # Resource detection configuration
    detectors: [env, system]
    timeout: 2s
  signozspanmetrics/delta:
    # Span metrics processor configuration
    metrics_exporter: clickhousemetricswrite
    metrics_flush_interval: 60s
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 1400ms, 2000ms, 5s, 10s, 20s, 40s, 60s ]
    dimensions_cache_size: 100000
    aggregation_temporality: AGGREGATION_TEMPORALITY_DELTA
    enable_exp_histogram: true
    dimensions:
      - name: service.namespace
        default: default
      - name: deployment.environment
        default: default
      # Ensure time series uniqueness
      - name: signoz.collector.id
      - name: service.version
      - name: browser.platform
      - name: browser.mobile
      - name: k8s.cluster.name
      - name: k8s.node.name
      - name: k8s.namespace.name
      - name: host.name
      - name: host.type
      - name: container.name

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777

exporters:
  clickhousetraces:
    # ClickHouse traces exporter configuration
    datasource: tcp://clickhouse:9000/signoz_traces
    low_cardinal_exception_grouping: ${env:LOW_CARDINAL_EXCEPTION_GROUPING}
    use_new_schema: true
  clickhousemetricswrite:
    # ClickHouse metrics write exporter configuration
    endpoint: tcp://clickhouse:9000/signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true
  signozclickhousemetrics:
    # SigNoz ClickHouse metrics exporter configuration
    dsn: tcp://clickhouse:9000/signoz_metrics
  clickhouselogsexporter:
    # ClickHouse logs exporter configuration
    dsn: tcp://clickhouse:9000/signoz_logs
    timeout: 10s
    use_new_schema: true

service:
  # Telemetry configuration
  telemetry:
    logs:
      encoding: json
      level: ${env:LOG_LEVEL}
      development: ${env:DEBUG}
    metrics:
      address: 0.0.0.0:8888
  # Extensions configuration
  extensions:
    - health_check
    - pprof
  # Pipeline configuration
  pipelines:
    # Traces pipeline
    traces:
      receivers: [otlp]
      processors: [signozspanmetrics/delta, batch]
      exporters: [clickhousetraces]
    # Metrics pipeline
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousemetricswrite, signozclickhousemetrics]
    # Logs pipeline
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouselogsexporter]
